on:
  issues:
    types: [opened, edited]

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.MY_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          echo $ISSUE_URL
          gh issue edit $ISSUE_URL --add-label "triage"

